# configs/logger/wandb.yaml
_target_: pytorch_lightning.loggers.WandbLogger

project: "faithful-cond-gen"
name: "debug_run_celeba"
save_dir: "./outputs"
offline: false  # Set to true if you don't have internet access on the node
id: null        # Set this to resume a specific run ID
log_model: false