# configs/config_rxrx1.yaml
defaults:
  - dataset: rxrx1
  - model: generator_rxrx1
  - pl_module: default
  - variant: vanilla        # vanilla, repa, compositional, repa_compositional, attr_delta
  - train: default_rxrx1
  - eval: rfid
  - logger: wandb_rxrx1
  - callbacks: checkpoint
  - _self_

seed: 1337
device: cuda