# configs/config.yaml
defaults:
  - dataset: rxrx1        # celeba, rxrx1
  - model: generator_rxrx1 # generator_celeba, generator_rxrx1
  - pl_module: default     # GeneratorPL settings (lr, etc)
  - train: debug           # Trainer settings (50 batches)
  - eval: rfid
  - logger: wandb          # WandB Logger
  - _self_

seed: 1337
device: cuda