# configs/train/debug.yaml
_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 8
strategy: auto
num_nodes: 1

max_epochs: 1
limit_train_batches: 50   # The "Quick Run" constraint
limit_val_batches: 5
log_every_n_steps: 10

enable_checkpointing: false
default_root_dir: "./outputs/debug_run"